name: Publish Extension
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Zip extension
        run: zip -r PaaP.zip _locales icons manifest.json rules.json -x icons/icon.svg

      - name: Get latest tag
        id: get_latest_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
        if: github.event_name != 'push'

      - name: Release to GitHub
        uses: softprops/action-gh-release@v3
        with:
          files: PaaP.zip
          generate_release_notes: true
          tag_name: ${{ github.event_name == 'push' && github.ref_name || steps.get_latest_tag.outputs.tag }}

      - name: Publish to Firefox Add-ons
        uses: wdzeng/firefox-addon@v1
        with:
          addon-guid: paap.itf@npg418.com
          xpi-path: PaaP.zip
          license: MIT
          jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
          jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}
