name: Publish Extension
on:
  release:
    types: [published]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Zip extension
        run: zip _locales icons manifest.json rules.json -r PaaP.zip -x icons/icon.svg

      - name: Publish to Firefox Add-ons
        uses: wdzeng/firefox-addon@v1
        with:
          addon-guid: paap.itf@npg418.com
          xpi-path: PaaP.zip
          license: MIT
          jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
          jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}
